const testData = [
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0P2TarcS_M_0ALXH',
    _score: 1,
    _source: {
      postDate: '2017-01-04T02:31:31-0800',
      description: "<section id=\"postingbody\">\n        <div class=\"print-information print-qrcode-container\">\n            <p class=\"print-qrcode-label\">QR Code Link to This Post</p>\n            <div class=\"print-qrcode\" data-location=\"http://sfbay.craigslist.org/sby/sys/5944734868.html\"></div>\n        </div>\nI have 2010 MacBook Pro model excellent condition just put new battery had to computer refurbished a new battery installed just recently bought a new MacBook Pro so I no longer need my older model it's in great shape a good started computer for someone original price for this computer when I first bought it for $1500 I'm pretty firm at $375but will negotiate.<br>\n\t<br>\n    </section>",
      title: '2010 MacBook pro 375 awesome computer',
      sellerEmail: '',
      price: '$375',
      postingUrl: 'http://sfbay.craigslist.org/sby/sys/5944734868.html',
      cityName: ' (san jose west)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sys/5944734868',
      long: '-121.915300',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-04T19:15:10-0800',
      lat: '37.324900',
      attributes: [],
      postId: '5944734868',
      imageUrls: [
        'https://images.craigslist.org/00202_9vJUs6k0y30_600x450.jpg',
        'https://images.craigslist.org/00W0W_inislC6dyFG_600x450.jpg',
        'https://images.craigslist.org/00h0h_irVsHveduNb_600x450.jpg',
        'https://images.craigslist.org/00Q0Q_7C6UmIMoLg9_600x450.jpg',
        'https://images.craigslist.org/00h0h_cNmn0MFPqA2_600x450.jpg',
        'https://images.craigslist.org/00202_9mODMDJLJ0h_600x450.jpg',
      ],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0P7RarcS_M_0ALXK',
    _score: 1,
    _source: {
      postDate: '2017-01-03T23:02:57-0800',
      description: "<section id=\"postingbody\">\n        <div class=\"print-information print-qrcode-container\">\n            <p class=\"print-qrcode-label\">QR Code Link to This Post</p>\n            <div class=\"print-qrcode\" data-location=\"http://sfbay.craigslist.org/sfc/sys/5944673100.html\"></div>\n        </div>\nSelling my MacBook Pro since I just upgraded to the latest one.<br>\nIt's in really good shape with absolutely no scratches anywhere but the bottom of the laptop, and only very minor ones there too.<br>\nI ran a disk test to make sure the SSD is still in perfect working order. Never had any issues with this computer and it hasn't really been used that much overall.<br>\nKeys show almost no signs of wear and the screen has no marks or signs of wear at all.<p>\n\nSee full specs here:\nhttps://support.apple.com/kb/sp653?locale=en_US\n</p><p>\nMacBook Pro (Retina, Mid 2012)<br>\nProcessor: 2.6 GHz Intel Quad Core i7<br>\nMemory: 16 GB 1600 MHz DDR3<br>\nGraphic: Intel HD Graphics 4000 1536 MB<br>\nStorage: 512GB SDD Drive<br>\nNumber of Processors: 1<br>\n  Total Number of Cores: 4<br>\n  L2 Cache (per Core): 256 KB<br>\n  L3 Cache: 6 MB<br>\nDisplay Type:\tMatte LCD<br>\n  Resolution:\t1680 x 1050 <br>\nBrand new install of OS 10.12.2 Sierra</p>    </section>",
      title: 'Apple MacBook Pro 15" (Mid 2012), 2.6Ghz i7, 16GB RAM, 512 GB SSD',
      sellerEmail: '',
      price: '$1000',
      postingUrl: 'http://sfbay.craigslist.org/sfc/sys/5944673100.html',
      cityName: ' (castro / upper market)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sys/5944673100',
      long: '-122.431211',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-04T13:19:20-0800',
      lat: '37.767492',
      attributes: [
        '<p class="attrgroup">\n           <span>condition: <b>excellent</b></span><br>\n           <span>make / manufacturer: <b>Apple</b></span><br>\n           <span>model name / number: <b>A1286</b></span><br>\n   </p>',
      ],
      postId: '5944673100',
      imageUrls: [
        'https://images.craigslist.org/00Q0Q_lDexoXeToyM_600x450.jpg',
        'https://images.craigslist.org/00h0h_9GBarOjPm0t_600x450.jpg',
        'https://images.craigslist.org/01313_17zGn4WiK2T_600x450.jpg',
        'https://images.craigslist.org/00n0n_clMq2mFFy4_600x450.jpg',
        'https://images.craigslist.org/00E0E_cnnZvVpArkp_600x450.jpg',
        'https://images.craigslist.org/00j0j_k6N4ImvnCGv_600x450.jpg',
        'https://images.craigslist.org/00e0e_8sr2XP0bSbt_600x450.jpg',
        'https://images.craigslist.org/00s0s_4Pl8ReE1IvZ_600x450.jpg',
        'https://images.craigslist.org/01111_4eDsVN2z72b_600x450.jpg',
        'https://images.craigslist.org/00J0J_7YtBaE9vq5X_600x450.jpg',
        'https://images.craigslist.org/00Z0Z_lPenZbuBG2w_600x450.jpg',
        'https://images.craigslist.org/01717_laQUTacFmNp_600x450.jpg',
      ],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0Q0FarcS_M_0ALXY',
    _score: 1,
    _source: {
      postDate: '2016-12-06T22:24:48-0800',
      description: "<section id=\"postingbody\">\n        <div class=\"print-information print-qrcode-container\">\n            <p class=\"print-qrcode-label\">QR Code Link to This Post</p>\n            <div class=\"print-qrcode\" data-location=\"http://sfbay.craigslist.org/sby/sys/5908918547.html\"></div>\n        </div>\nMacBook Pro 15\" RETINA/Late 2013/2.0GHz Intel i7/16GB/256GB SSD/Excellent LAPTOP!<br>\n<br>\nPLEASE NOTE THIS IS A LATE 2013 MODEL WHICH USES THE NEWER HASWELL INTEL ARCHITECTURE! Has a manufacture date of Jan. 2014, see coconut report screenshot.<br>\n<br>\nOnly 71 Cycles on it, with about 96-97% of original capacity! NEARLY NEW!  See coconut battery report!<br>\n<br>\nTHIS a 9.5/10 CONDITION MACBOOK PRO! NO MAJOR COSMETICS ISSUES only one scratch on bottom of laptop which is noticeable.<br>\n<br>\nRunning macOS 10.12.2! EFI Firmware Update Done! COMES WITH MS OFFICE 2016 (Updated to Dec. 2016 Package). FINAL CUT PRO 2016 and LOGIC PRO X 2016 INSTALLED.<br>\n<br>\nWILL Come with a Apple OEM 85W Magsafe 2 Charger with Wall Plug + AC Extension that has been 100% Tested! THE KEYS ARE PERFECT AND CLEAN! I have used a combo of special solution to clean the entire laptop.<br>\n<br>\n*** This will be tied to a Bill of Sale! 30-Day Warranty included in writing from our business which will guarantee you won't have any issues with the machine! ***<br>\n<br>\nWWW.KPLUSCOMPUTERS.TECH is our website. We perform IT managed services for SMB's and are Independent Apple Sellers.<br>\n<br>\nPlease e-mail me ASAP with your contact # if you wish to speak with me. I will not accept trades, this is a cash only sale. No personal checks. I will not respond to text messages.    </section>",
      title: 'MacBook Pro 15" RETINA/2013/2.0GHz Intel i7/16GB/256GB SSD/VERY GOOD!!',
      sellerEmail: '',
      price: '$1050',
      postingUrl: 'http://sfbay.craigslist.org/sby/sys/5908918547.html',
      cityName: ' (san jose south)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sys/5908918547',
      long: '-121.889600',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-03T16:36:26-0800',
      lat: '37.256800',
      attributes: [
        '<p class="attrgroup">\n           <span>condition: <b>excellent</b></span><br>\n   </p>',
      ],
      postId: '5908918547',
      imageUrls: [
        'https://images.craigslist.org/01414_4kotNu6NjnB_600x450.jpg',
        'https://images.craigslist.org/00v0v_7kh106LEKH5_600x450.jpg',
        'https://images.craigslist.org/00D0D_8qfbx0jrqff_600x450.jpg',
        'https://images.craigslist.org/00x0x_5xuIVMMlW4y_600x450.jpg',
        'https://images.craigslist.org/00n0n_be2IGScx2SB_600x450.jpg',
        'https://images.craigslist.org/00T0T_cyEqE5gjzSG_600x450.jpg',
        'https://images.craigslist.org/00J0J_1OtsJ3250o2_600x450.jpg',
        'https://images.craigslist.org/00h0h_9ZYgcs1nCLW_600x450.jpg',
        'https://images.craigslist.org/00f0f_4zpXa9int5o_600x450.jpg',
      ],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0RErarcS_M_0ALXl',
    _score: 1,
    _source: {
      postDate: '2016-12-28T15:41:32-0800',
      description: '<section id="postingbody">\n        <div class="print-information print-qrcode-container">\n            <p class="print-qrcode-label">QR Code Link to This Post</p>\n            <div class="print-qrcode" data-location="http://sfbay.craigslist.org/sby/mob/5936615845.html"></div>\n        </div>\nWanted to buy iPhones 7/ip7+/gift cards/macbook/ipads..etc. Text me at <br>\n <a href="/fb/sfo/mob/5936615845" class="showcontact" title="click to show contact info" rel="nofollow">show contact info</a><br>\n    </section>',
      title: 'wanted iPhones gift cards macbook iPads..etc',
      sellerEmail: '',
      price: '$11111',
      postingUrl: 'http://sfbay.craigslist.org/sby/mob/5936615845.html',
      cityName: null,
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/mob/5936615845',
      long: '-121.854515',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-03T14:36:25-0800',
      lat: '37.375614',
      attributes: [
        '<p class="attrgroup">\n           <span>mobile OS: <b>apple iOS</b></span><br>\n   </p>',
      ],
      postId: '5936615845',
      imageUrls: [],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0RbaarcS_M_0ALX0',
    _score: 1,
    _source: {
      postDate: '2016-12-12T12:59:49-0800',
      description: '<section id="postingbody">\n        <div class="print-information print-qrcode-container">\n            <p class="print-qrcode-label">QR Code Link to This Post</p>\n            <div class="print-qrcode" data-location="http://sfbay.craigslist.org/sby/sop/5916623621.html"></div>\n        </div>\nModel A1436<br>\n<br>\nThe 45-Watt MagSafe Power Adapter for MacBook Air features a magnetic DC connector that ensures your power cable will disconnect if it experiences undue strain and helps prevent fraying or weakening of the cables over time. In addition, the magnetic DC helps guide the plug into the system for a quick and secure connection.<br>\nWhen the connection is secure, an LED located at the head of the DC connector will light; an amber light lets you know that your portable is charging, while a green light tells you that you have a full charge. An AC cord is provided with the adapter for maximum cord length, while the AC wall adapter (also provided) gives users an even easier and more compact way to travel.<br>\nRedesigned specifically for MacBook Air, the adapter is the perfect traveling companion. It has a clever design which allows the DC cable to be wound neatly around itself for easy cable storage.<br>\nThis power adapter recharges the lithium polymer battery while the system is off, on, or in sleep mode. It also powers the system if you choose to operate without a battery.<br>\nCompatible only with MacBook Air with MagSafe Power Port.    </section>',
      title: 'Genuine Apple Magsafe 45W ForPower Adapter for MacBook Air',
      sellerEmail: '',
      price: '$35',
      postingUrl: 'http://sfbay.craigslist.org/sby/sop/5916623621.html',
      cityName: ' (saratoga)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sop/5916623621',
      long: '-122.022700',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-02T20:56:10-0800',
      lat: '37.271300',
      attributes: [],
      postId: '5916623621',
      imageUrls: [],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0RdZarcS_M_0ALX4',
    _score: 1,
    _source: {
      postDate: '2016-12-12T13:07:49-0800',
      description: '<section id="postingbody">\n        <div class="print-information print-qrcode-container">\n            <p class="print-qrcode-label">QR Code Link to This Post</p>\n            <div class="print-qrcode" data-location="http://sfbay.craigslist.org/sby/sop/5916636604.html"></div>\n        </div>\nApple 85W MagSafe Power Adapter (for 15- and 17-inch MacBook Pro) <br>\nThis is brand new and the original wrapper is still on it.<br>\n<br>\nThe 85 Watt MagSafe Power Adapter features a magnetic DC connector that ensures your power cable will disconnect if it experiences undue strain and helps prevent fraying or weakening of the cables over time. In addition, the magnetic DC helps guide the plug into the system for a quick and secure connection.<br>\nWhen the connection is secure, an LED located at the head of the DC connector will light; an amber light lets you know that your portable is charging, while a green light tells you that you have a full charge. An AC cord is provided with the adapter for maximum cord length, while the AC wall adapter (also provided) gives users an even easier and more compact way to travel.<br>\nDesigned to be the perfect traveling companion, the adapter has a clever design which allows the DC cable to be wound neatly around itself for easy cable storage.<br>\nThis power adapter recharges the lithium polymer battery while the system is off, on, or in sleep mode. It also powers the system if you choose to operate without a battery.<br>\nCompatible with 15- or 17-inch MacBook Pro.<br>\n<br>\nProduct Description<br>\nCompatible Models: MacBook Pro MagSafe A1244 Brand New Video Features Output Amp:4.6A Video Features Output Voltage:18.5V Video Features Output Watt:85W Model: MA463LL/A, MA464LL/A, MA090LL, MA600LL, MA601LL, MA092LL/A, MA609LL, MA610LL, MA611LL/A, MA895LL/A, MA896LL/A, MA895LL, MA896LL, MA897LL/A, Core Duo 1.67 15-inch, 15.4-inch Glossy, 17-inch, Late 2006, Mid 2007 17-inch 85-watt power adapter Powers the lithium-ion battery while system is off, on or in sleep mode. Also charges without the battery present for added convenience. LED indicator lights Display charge status. AC Input: 100 AC-240 AC(50/60HZ) Output( V /A ):18.5V 4.6Amp Output Power(W): 85W Connector.    </section>',
      title: 'Genuine Apple Magsafe 85W For Macbook Pro A1244 W/Power Cord',
      sellerEmail: '',
      price: '$40',
      postingUrl: 'http://sfbay.craigslist.org/sby/sop/5916636604.html',
      cityName: ' (saratoga)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sop/5916636604',
      long: '-122.022700',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-02T20:56:47-0800',
      lat: '37.271300',
      attributes: [
        '<p class="attrgroup">\n           <span>make / manufacturer: <b>Apple</b></span><br>\n           <span>model name / number: <b>The 85 Watt MagSafe Power Adapte</b></span><br>\n   </p>',
      ],
      postId: '5916636604',
      imageUrls: [
        'https://images.craigslist.org/00d0d_4Ozt49FLDM8_600x450.jpg',
        'https://images.craigslist.org/00f0f_6Qvbho5I8Zu_600x450.jpg',
      ],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0SGBarcS_M_0ALYd',
    _score: 1,
    _source: {
      postDate: '2016-12-27T20:27:21-0800',
      description: '<section id="postingbody">\n        <div class="print-information print-qrcode-container">\n            <p class="print-qrcode-label">QR Code Link to This Post</p>\n            <div class="print-qrcode" data-location="http://sfbay.craigslist.org/sby/sys/5935466672.html"></div>\n        </div>\nSelling an excellent mint condition MacBook Pro 13in 2015 model w/ Japanese keyboard layout. Original box, all manuals and charger included.<br>\n<br>\nModel: MF839LL/J<br>\nOriginally released March 2015<br>\n13.3-inch (diagonal) Retina display; 2560-by-1600 resolution at 227 pixels per inch<br>\n8GB of 1866MHz LPDDR3 onboard memory<br>\n128GB PCIe-based flash storage<br>\n720p FaceTime HD camera<br>\nIntel Iris Graphics 6100<br>\nProcessor Type:\tIntel Core i5<br>\nProcessor Speed:\t2.70GHz\t<br>\nProduct Family:\tMacBook Pro<br>\nOperating System:\tMac OS X 10.10, Yosemite<br>\n<br>\nNo international shipping (US ONLY)<br>\nYour item will be shipped once payment is received.<br>\nYou can also come pick up the item or I can hand deliver it to you (SF Bay Area only)    </section>',
      title: 'Apple 13.3" MacBook Pro Retina & ForceTouch MF839L/J',
      sellerEmail: '',
      price: '$850',
      postingUrl: 'http://sfbay.craigslist.org/sby/sys/5935466672.html',
      cityName: ' (santa clara)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sys/5935466672',
      long: '-121.996779',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-02T02:28:55-0800',
      lat: '37.338159',
      attributes: [
        '<p class="attrgroup">\n           <span>condition: <b>excellent</b></span><br>\n           <span>make / manufacturer: <b>Apple</b></span><br>\n           <span>model name / number: <b>MF839LL/J</b></span><br>\n           <span>size / dimensions: <b>12.78x0.95x8.4</b></span><br>\n   </p>',
      ],
      postId: '5935466672',
      imageUrls: [
        'https://images.craigslist.org/00P0P_f0VFVx2KxLc_600x450.jpg',
        'https://images.craigslist.org/00G0G_iFhQvLQcA2c_600x450.jpg',
        'https://images.craigslist.org/00n0n_9trAalaUwXw_600x450.jpg',
      ],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0SnjarcS_M_0ALYj',
    _score: 1,
    _source: {
      postDate: '2016-12-09T21:35:44-0800',
      description: "<section id=\"postingbody\">\n        <div class=\"print-information print-qrcode-container\">\n            <p class=\"print-qrcode-label\">QR Code Link to This Post</p>\n            <div class=\"print-qrcode\" data-location=\"http://sfbay.craigslist.org/eby/sys/5913189434.html\"></div>\n        </div>\napple laptop macbook air 11'' i5 1.6ghz 4gb ram 128 SSD $750<br>\n<br>\nmacOS Sierra MS Office +  final cut pro<br>\n<br>\napple warranty august 2017 <br>\n<br>\ntext or call only : \n <a href=\"/fb/sfo/sys/5913189434\" class=\"showcontact\" title=\"click to show contact info\" rel=\"nofollow\">show contact info</a>\n<br>\n<br>\nNo Nigerian Scam . No Paypal Scam    </section>",
      title: "macbook air 11'' i5 4gb ram apple warranty",
      sellerEmail: '',
      price: '$750',
      postingUrl: 'http://sfbay.craigslist.org/eby/sys/5913189434.html',
      cityName: ' (fremont / union city / newark)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sys/5913189434',
      long: null,
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-01T14:16:46-0800',
      lat: null,
      attributes: [],
      postId: '5913189434',
      imageUrls: [
        'https://images.craigslist.org/00O0O_iuisYB1YNBT_600x450.jpg',
        'https://images.craigslist.org/00000_cexx8pGuXH0_600x450.jpg',
        'https://images.craigslist.org/00K0K_6r9ZLcvEUXx_600x450.jpg',
        'https://images.craigslist.org/00e0e_elAUXwCpDJK_600x450.jpg',
        'https://images.craigslist.org/00a0a_ccacpNvTy0t_600x450.jpg',
        'https://images.craigslist.org/00s0s_PS6frKIwG1_600x450.jpg',
      ],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0OiHarcS_M_0ALWh',
    _score: 1,
    _source: {
      postDate: '2017-01-01T12:12:17-0800',
      description: '<section id="postingbody">\n        <div class="print-information print-qrcode-container">\n            <p class="print-qrcode-label">QR Code Link to This Post</p>\n            <div class="print-qrcode" data-location="http://sfbay.craigslist.org/pen/sys/5941126878.html"></div>\n        </div>\n2010 Macbook Pro with OS X Yosemite installed. Mid-2010 model, 2.4 Ghz Intel Core 2 Duo processor, 4 GB DDR3 memory, upgradable to 8 (and I believe 12 too, technically) to massively increase performance. NVIDIA GeForce 320M 256 MB graphics card.<br>\n<br>\nGood condition, screen is excellent. Works fine - just slower than newer Macbooks. All keys present and in good shape, trackpad fully functional and responsive. Plenty of little dings and scratches, but nothing extreme. Rubber feet are missing, super easy and cheap replacement if you care about them. Drive has been wiped for new user to start fresh!<br>\n<br>\nGreat starter computer for young people, or easy modding experiment for advanced users. These older Apple laptops are really easy to get inside and work on, so for an extra hundred dollars and an hour of tinkering this can become twice the computer it is today!<br>\n<br>\nOpen to reasonable offers!    </section>',
      title: '2010 Macbook Pro, 2.4 Ghz Core 2 duo, 4gb ram',
      sellerEmail: '',
      price: '$400',
      postingUrl: 'http://sfbay.craigslist.org/pen/sys/5941126878.html',
      cityName: ' (san carlos)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sys/5941126878',
      long: '-122.267400',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-02T09:58:23-0800',
      lat: '37.496900',
      attributes: [
        '<p class="attrgroup">\n           <span>condition: <b>good</b></span><br>\n           <span>make / manufacturer: <b>apple</b></span><br>\n           <span>model name / number: <b>macbook pro</b></span><br>\n           <span>size / dimensions: <b>13 inch</b></span><br>\n   </p>',
      ],
      postId: '5941126878',
      imageUrls: [
        'https://images.craigslist.org/00M0M_u3YiNvEU0y_600x450.jpg',
        'https://images.craigslist.org/00y0y_sQmXEEr0ka_600x450.jpg',
        'https://images.craigslist.org/00H0H_cE062xVohcb_600x450.jpg',
        'https://images.craigslist.org/00n0n_5htt0Oarnur_600x450.jpg',
        'https://images.craigslist.org/01717_dWdUD1CrcIY_600x450.jpg',
        'https://images.craigslist.org/00j0j_aMTTepAEYRj_600x450.jpg',
        'https://images.craigslist.org/00T0T_fD3xSvrARs9_600x450.jpg',
        'https://images.craigslist.org/00909_9Y8rxqU5DmU_600x450.jpg',
        'https://images.craigslist.org/01010_1EWTV9KhmxR_600x450.jpg',
      ],
      sellerName: '',
    },
  },
  {
    _index: 'cl',
    _type: 'listing',
    _id: 'AVls0Px0arcS_M_0ALXA',
    _score: 1,
    _source: {
      postDate: '2016-12-16T08:56:07-0800',
      description: "<section id=\"postingbody\">\n        <div class=\"print-information print-qrcode-container\">\n            <p class=\"print-qrcode-label\">QR Code Link to This Post</p>\n            <div class=\"print-qrcode\" data-location=\"http://sfbay.craigslist.org/sby/sys/5921775592.html\"></div>\n        </div>\nmStand is made of a single solid piece of aluminum matching MacBook Pro, MacBook Air, and MacBook's anodized finish. It transforms your notebook into a stable and stylish workstation.<br>\n<br>\nMore information from Apple's Website: <br>\nhttp://www.apple.com/shop/product/TN740ZM/A/rain-design-mstand-for-macbook-pro-macbook-air-macbook<br>\n<br>\nRetail: $49.95<br>\n<br>\nSpecs: <br>\nMaterial: Aluminum<br>\nHeight: 5.9 in./15 cm<br>\nLength: 10 in./25.4 cm<br>\nWidth: 7.5 in./19.05 cm<br>\nWeight: 3 lb./1.36 kg    </section>",
      title: 'Silver Rain Design mStand for MacBook Pro/MacBook Air/MacBook',
      sellerEmail: '',
      price: '$30',
      postingUrl: 'http://sfbay.craigslist.org/sby/sys/5921775592.html',
      cityName: ' (mountain view)',
      sellerUrl: 'http://sfbay.craigslist.org/reply/sfo/sys/5921775592',
      long: '-122.078300',
      sellerPhoneNumber: '',
      specs: [],
      updateDate: '2017-01-04T11:08:31-0800',
      lat: '37.389300',
      attributes: [
        '<p class="attrgroup">\n           <span>condition: <b>like new</b></span><br>\n           <span>make / manufacturer: <b>Apple</b></span><br>\n   </p>',
      ],
      postId: '5921775592',
      imageUrls: [],
      sellerName: '',
    },
  },
];

export default testData;
