FROM node:latest

# Create app directory
RUN mkdir -p /gatewayServer
RUN mkdir -p /config
WORKDIR /gatewayServer

# Install app dependencies
COPY /gatewayServer/package.json /gatewayServer
RUN npm install

# Bundle app source
COPY ./gatewayServer /gatewayServer
COPY ./config /config

EXPOSE 3000
CMD [ "npm", "start" ]